env:
  githubEmail: oliver.nelson@icloud.com
  deployToRepo: hendo


name: Generate markdown and publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "* 12 * * *"

jobs:
  Generate-Markdown:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./generator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache-dependency-path: ./generator/package-lock.json
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: node dist/genMarkdown.js --NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID}} --NOTION_API_KEY=${{ secrets.NOTION_API_KEY}}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "generate markdown" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./astro

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies with npm
      - name: Install dependencies
        run: npm i

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      # Push to your pages repo
      - name: Push to pages repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'astro/dist'
          destination-github-username: ${{ github.actor }}
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: ${{ env.githubEmail }}
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: gh-pages
